name: Report a bug / issue
description: Report an issue with the integration - PLEASE KEEP IT IN ENGLISH!
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Note:
        This issue form is for reporting bugs only!
        KEEP THE LANGUAGE AT ENGLISH PLEASE!

        PLEASE MAKE SURE YOU HAVE INSTALLED THE LATEST VERSION BEFORE SUBMITTING A NEW ISSUE!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the issue
      description: >-
        Describe the issue you are experiencing here.
        Describe what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core has the issue?
      placeholder: core-
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
  - type: input
    attributes:
      label: What was the last working version of Home Assistant Core?
      placeholder: core-
      description: >
        If known, otherwise leave blank.
  - type: input
    validations:
      required: true
    attributes:
      label: What version of the Landroid Cloud integration do you have installed
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: input
    validations:
      required: true
    attributes:
      label: Which make and model is the mower used for this integration?
      placeholder: Worx WRxyz or Landroid M500
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    validations:
      required: true
    attributes:
      label: Diagnostics information (NOT log entries!)
      placeholder: "drag-and-drop the diagnostics data file here (do not copy-and-paste the content)"
      description: >-
        This integrations provide the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).

        **It would really help if you could download the diagnostics data for the device you are having issues with,
        and <ins>drag-and-drop that file into the textbox below.</ins>**

        It generally allows pinpointing defects and thus resolving issues faster.

        If you are unable to provide the diagnostics (ie. you cannot add the integration), please write **None** in this field.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Relevant log entries
      description: >-
        Anything from home-assistant.log that has any direct relevance for this issue

        If you are unable to provide any relevant log entries, please write **None** in this field.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
