"""Attribute map used by Landroid Cloud integration."""
from __future__ import annotations

ATTR_MAP = {
    "default": {
        "state": {
            "id": "id",
            "error_description": "error_description",
            "blade_time": "total_blade_time",
            "blade_time_current": "current_blade_time",
            "blade_work_time_reset_at": "blade_time_reset",
            "battery_voltage": "battery_voltage",
            "battery_temperature": "battery_temperature",
            "battery_charge_cycle": "total_charge_cycles",
            "battery_charge_cycle_current": "current_charge_cycles",
            "battery_charge_cycles_reset_at": "charge_cycles_reset",
            "work_time": "work_time",
            "distance": "distance",
            "updated": "last_update",
            "rssi": "rssi",
            "yaw": "yaw",
            "roll": "roll",
            "pitch": "pitch",
            "gps_latitude": "latitude",
            "gps_longitude": "longitude",
            "rain_delay": "raindelay",
            "schedule_variation": "timeextension",
            "firmware": "firmware_version",
            "serial": "serial",
            "mac": "mac",
            "schedule_mower_active": "schedule_enabled",
            "partymode_enabled": "partymode_enabled",
            "mowing_zone": "mowing_zone",
            "locked": "locked",
            "online": "online",
            "accessories": "accessories",
            "zone": "zone",
            "zone_probability": "zone_probability",
            "schedules": "schedules",
        },
        "icon": "mdi:robot-mower",
        "unit": None,
        "device_class": None,
    },
}
